meta_product_name: "Save Car"
meta_title: "Save Car - Ajuda que você precisa"
meta_description: "Removemos Seu Carro Com Urgência. Atendimento Online. Equipe Qualificada."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards