# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


winch_params = [
   "Acura",
   "Alfa Romeo",
   "Asia",
   "Aston Martin",
   "Audi",
   "Bentley",
   "BMW",
   "Buggy BRM",
   "Buick",
   "Cadillac",
   "Carver Concept",
   "Chamonix",
   "Changan (Chana)",
   "Chery"
   "Chevrolet",
   "Chrysler",
   "Citroën",
   "CN Auto",
   "Crosslander",
   "Daewoo",
   "Daihatsu",
   "Dodge",
   "DS",
   "Effa",
   "Engesa",
   "Envemo",
   "Fargo",
   "Ferrari",
   "Fiat",
   "Ford",
   "Fyber Buggy",
   "Geely",
   "GMC",
   "Great Wall",
   "Gurgel",
   "Hafei Towner",
   "Haima",
   "HITECH ELECTRIC",
   "Honda",
   "Hummer",
   "Hyundai",
   "Infiniti",
   "Isuzu",
   "Iveco",
   "Jac",
   "Jaguar",
   "Jeep",
   "Jin Bei",
   "Jonway",
   "JPX",
   "Kia",
   "Lada",
   "Lamborghini",
   "Land Rover",
   "Landwind",
   "Lexus",
   "Lifan",
   "Lincoln",
   "Lobini",
   "Lotus",
   "Mahindra",
   "Maserati",
   "Matra",
   "Mazda",
   "McLaren",
   "Mercedes-Benz",
   "MG",
   "MG Spaic",
   "MINI",
   "Mitsubishi",
   "Nissan",
   "Oldsmobile",
   "Pagani",
   "Peugeot",
   "Plymouth",
   "Pontiac",
   "Porsche",
   "Rely",
   "Renault",
   "Rolls-Royce",
   "Saab",
   "Saturn",
   "Seat",
   "Shineray",
   "Shuanghuan",
   "Smart",
   "Spyker",
   "SsangYong",
   "Subaru",
   "Sunbeam",
   "Suzuki",
   "Tac",
   "Tesla",
   "Toyota",
   "Troller",
   "Volkswagen",
   "Volvo",
  ]
